server:
  port: 5000

spring:
  # Profiles configuration
  profiles: prod
  # Database configuration
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  # JPA configuration
  jpa:
    hibernate:
      ddl-auto: update
      # Avoid issue with JPA case insensitive
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
    show-sql: false
    database: postgresql
    # PotGIS configuration
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
          batch_size: 30
          generate_statistics: true